//
// BikePointAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire
import RxSwift



open class BikePointAPI: APIBase {
    /**
     Gets the bike point with the given id.
     
     - parameter id: (path) A bike point id (a list of ids can be obtained from the above BikePoint call) 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func bikePointGet(id: String, completion: @escaping ((_ data: Place?,_ error: Error?) -> Void)) {
        bikePointGetWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     Gets the bike point with the given id.
     
     - parameter id: (path) A bike point id (a list of ids can be obtained from the above BikePoint call) 
     - returns: Observable<Place>
     */
    open class func bikePointGet(id: String) -> Observable<Place> {
        return Observable.create { observer -> Disposable in
            bikePointGet(id: id) { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     Gets the bike point with the given id.
     - GET /BikePoint/{id}
     - examples: [{contentType=application/json, example={
  "commonName" : "aeiou",
  "placeType" : "aeiou",
  "distance" : 1.3579000000000001069366817318950779736042022705078125,
  "children" : [ "" ],
  "childrenUrls" : [ "aeiou" ],
  "lon" : 1.3579000000000001069366817318950779736042022705078125,
  "id" : "aeiou",
  "additionalProperties" : [ {
    "sourceSystemKey" : "aeiou",
    "modified" : "2000-01-23T04:56:07.000+00:00",
    "category" : "aeiou",
    "value" : "aeiou",
    "key" : "aeiou"
  } ],
  "url" : "aeiou",
  "lat" : 1.3579000000000001069366817318950779736042022705078125
}}, {contentType=application/xml, example=<null>
  <id>aeiou</id>
  <url>aeiou</url>
  <commonName>aeiou</commonName>
  <distance>3.149</distance>
  <placeType>aeiou</placeType>
  <childrenUrls>aeiou</childrenUrls>
  <lat>3.149</lat>
  <lon>3.149</lon>
</null>}]
     - examples: [{contentType=application/json, example={
  "commonName" : "aeiou",
  "placeType" : "aeiou",
  "distance" : 1.3579000000000001069366817318950779736042022705078125,
  "children" : [ "" ],
  "childrenUrls" : [ "aeiou" ],
  "lon" : 1.3579000000000001069366817318950779736042022705078125,
  "id" : "aeiou",
  "additionalProperties" : [ {
    "sourceSystemKey" : "aeiou",
    "modified" : "2000-01-23T04:56:07.000+00:00",
    "category" : "aeiou",
    "value" : "aeiou",
    "key" : "aeiou"
  } ],
  "url" : "aeiou",
  "lat" : 1.3579000000000001069366817318950779736042022705078125
}}, {contentType=application/xml, example=<null>
  <id>aeiou</id>
  <url>aeiou</url>
  <commonName>aeiou</commonName>
  <distance>3.149</distance>
  <placeType>aeiou</placeType>
  <childrenUrls>aeiou</childrenUrls>
  <lat>3.149</lat>
  <lon>3.149</lon>
</null>}]
     
     - parameter id: (path) A bike point id (a list of ids can be obtained from the above BikePoint call) 

     - returns: RequestBuilder<Place> 
     */
    open class func bikePointGetWithRequestBuilder(id: String) -> RequestBuilder<Place> {
        var path = "/BikePoint/{id}"
        path = path.replacingOccurrences(of: "{id}", with: id.asParameter, options: .literal, range: nil)
        let URLString = RxTfLAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Place>.Type = RxTfLAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Gets all bike point locations. The Place object has an addtionalProperties array which contains the nbBikes, nbDocks and nbSpaces              numbers which give the status of the BikePoint. A mismatch in these numbers i.e. nbDocks - (nbBikes + nbSpaces) != 0 indicates broken docks.
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func bikePointGetAll(completion: @escaping ((_ data: [Place]?,_ error: Error?) -> Void)) {
        bikePointGetAllWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     Gets all bike point locations. The Place object has an addtionalProperties array which contains the nbBikes, nbDocks and nbSpaces              numbers which give the status of the BikePoint. A mismatch in these numbers i.e. nbDocks - (nbBikes + nbSpaces) != 0 indicates broken docks.
     
     - returns: Observable<[Place]>
     */
    open class func bikePointGetAll() -> Observable<[Place]> {
        return Observable.create { observer -> Disposable in
            bikePointGetAll() { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     Gets all bike point locations. The Place object has an addtionalProperties array which contains the nbBikes, nbDocks and nbSpaces              numbers which give the status of the BikePoint. A mismatch in these numbers i.e. nbDocks - (nbBikes + nbSpaces) != 0 indicates broken docks.
     - GET /BikePoint
     - examples: [{contentType=application/json, example=[ {
  "commonName" : "aeiou",
  "placeType" : "aeiou",
  "distance" : 1.3579000000000001069366817318950779736042022705078125,
  "children" : [ "" ],
  "childrenUrls" : [ "aeiou" ],
  "lon" : 1.3579000000000001069366817318950779736042022705078125,
  "id" : "aeiou",
  "additionalProperties" : [ {
    "sourceSystemKey" : "aeiou",
    "modified" : "2000-01-23T04:56:07.000+00:00",
    "category" : "aeiou",
    "value" : "aeiou",
    "key" : "aeiou"
  } ],
  "url" : "aeiou",
  "lat" : 1.3579000000000001069366817318950779736042022705078125
} ]}, {contentType=application/xml, example=<null>
  <id>aeiou</id>
  <url>aeiou</url>
  <commonName>aeiou</commonName>
  <distance>3.149</distance>
  <placeType>aeiou</placeType>
  <childrenUrls>aeiou</childrenUrls>
  <lat>3.149</lat>
  <lon>3.149</lon>
</null>}]
     - examples: [{contentType=application/json, example=[ {
  "commonName" : "aeiou",
  "placeType" : "aeiou",
  "distance" : 1.3579000000000001069366817318950779736042022705078125,
  "children" : [ "" ],
  "childrenUrls" : [ "aeiou" ],
  "lon" : 1.3579000000000001069366817318950779736042022705078125,
  "id" : "aeiou",
  "additionalProperties" : [ {
    "sourceSystemKey" : "aeiou",
    "modified" : "2000-01-23T04:56:07.000+00:00",
    "category" : "aeiou",
    "value" : "aeiou",
    "key" : "aeiou"
  } ],
  "url" : "aeiou",
  "lat" : 1.3579000000000001069366817318950779736042022705078125
} ]}, {contentType=application/xml, example=<null>
  <id>aeiou</id>
  <url>aeiou</url>
  <commonName>aeiou</commonName>
  <distance>3.149</distance>
  <placeType>aeiou</placeType>
  <childrenUrls>aeiou</childrenUrls>
  <lat>3.149</lat>
  <lon>3.149</lon>
</null>}]

     - returns: RequestBuilder<[Place]> 
     */
    open class func bikePointGetAllWithRequestBuilder() -> RequestBuilder<[Place]> {
        let path = "/BikePoint"
        let URLString = RxTfLAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[Place]>.Type = RxTfLAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Search for bike stations by their name, a bike point's name often contains information about the name of the street              or nearby landmarks, for example. Note that the search result does not contain the PlaceProperties i.e. the status              or occupancy of the BikePoint, to get that information you should retrieve the BikePoint by its id on /BikePoint/id.
     
     - parameter query: (query) The search term e.g. \&quot;St. James\&quot; 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func bikePointSearch(query: String, completion: @escaping ((_ data: [Place]?,_ error: Error?) -> Void)) {
        bikePointSearchWithRequestBuilder(query: query).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     Search for bike stations by their name, a bike point's name often contains information about the name of the street              or nearby landmarks, for example. Note that the search result does not contain the PlaceProperties i.e. the status              or occupancy of the BikePoint, to get that information you should retrieve the BikePoint by its id on /BikePoint/id.
     
     - parameter query: (query) The search term e.g. \&quot;St. James\&quot; 
     - returns: Observable<[Place]>
     */
    open class func bikePointSearch(query: String) -> Observable<[Place]> {
        return Observable.create { observer -> Disposable in
            bikePointSearch(query: query) { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     Search for bike stations by their name, a bike point's name often contains information about the name of the street              or nearby landmarks, for example. Note that the search result does not contain the PlaceProperties i.e. the status              or occupancy of the BikePoint, to get that information you should retrieve the BikePoint by its id on /BikePoint/id.
     - GET /BikePoint/Search
     - examples: [{contentType=application/json, example=[ {
  "commonName" : "aeiou",
  "placeType" : "aeiou",
  "distance" : 1.3579000000000001069366817318950779736042022705078125,
  "children" : [ "" ],
  "childrenUrls" : [ "aeiou" ],
  "lon" : 1.3579000000000001069366817318950779736042022705078125,
  "id" : "aeiou",
  "additionalProperties" : [ {
    "sourceSystemKey" : "aeiou",
    "modified" : "2000-01-23T04:56:07.000+00:00",
    "category" : "aeiou",
    "value" : "aeiou",
    "key" : "aeiou"
  } ],
  "url" : "aeiou",
  "lat" : 1.3579000000000001069366817318950779736042022705078125
} ]}, {contentType=application/xml, example=<null>
  <id>aeiou</id>
  <url>aeiou</url>
  <commonName>aeiou</commonName>
  <distance>3.149</distance>
  <placeType>aeiou</placeType>
  <childrenUrls>aeiou</childrenUrls>
  <lat>3.149</lat>
  <lon>3.149</lon>
</null>}]
     - examples: [{contentType=application/json, example=[ {
  "commonName" : "aeiou",
  "placeType" : "aeiou",
  "distance" : 1.3579000000000001069366817318950779736042022705078125,
  "children" : [ "" ],
  "childrenUrls" : [ "aeiou" ],
  "lon" : 1.3579000000000001069366817318950779736042022705078125,
  "id" : "aeiou",
  "additionalProperties" : [ {
    "sourceSystemKey" : "aeiou",
    "modified" : "2000-01-23T04:56:07.000+00:00",
    "category" : "aeiou",
    "value" : "aeiou",
    "key" : "aeiou"
  } ],
  "url" : "aeiou",
  "lat" : 1.3579000000000001069366817318950779736042022705078125
} ]}, {contentType=application/xml, example=<null>
  <id>aeiou</id>
  <url>aeiou</url>
  <commonName>aeiou</commonName>
  <distance>3.149</distance>
  <placeType>aeiou</placeType>
  <childrenUrls>aeiou</childrenUrls>
  <lat>3.149</lat>
  <lon>3.149</lon>
</null>}]
     
     - parameter query: (query) The search term e.g. \&quot;St. James\&quot; 

     - returns: RequestBuilder<[Place]> 
     */
    open class func bikePointSearchWithRequestBuilder(query: String) -> RequestBuilder<[Place]> {
        let path = "/BikePoint/Search"
        let URLString = RxTfLAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "query": query
        ])
        

        let requestBuilder: RequestBuilder<[Place]>.Type = RxTfLAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
