//
// CabwiseAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire
import RxSwift



open class CabwiseAPI: APIBase {
    /**
     Gets taxis and minicabs contact information
     
     - parameter lat: (query) Latitude 
     - parameter lon: (query) Longitude 
     - parameter optype: (query) Operator Type e.g Minicab, Executive, Limousine (optional)
     - parameter wc: (query) Wheelchair accessible (optional)
     - parameter radius: (query) The radius of the bounding circle in metres (optional)
     - parameter name: (query) Trading name of operating company (optional)
     - parameter maxResults: (query) An optional parameter to limit the number of results return. Default and maximum is 20. (optional)
     - parameter legacyFormat: (query) Legacy Format (optional)
     - parameter forceXml: (query) Force Xml (optional)
     - parameter twentyFourSevenOnly: (query) Twenty Four Seven Only (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func cabwiseGet(lat: Double, lon: Double, optype: String? = nil, wc: String? = nil, radius: Double? = nil, name: String? = nil, maxResults: Int32? = nil, legacyFormat: Bool? = nil, forceXml: Bool? = nil, twentyFourSevenOnly: Bool? = nil, completion: @escaping ((_ data: Object?,_ error: Error?) -> Void)) {
        cabwiseGetWithRequestBuilder(lat: lat, lon: lon, optype: optype, wc: wc, radius: radius, name: name, maxResults: maxResults, legacyFormat: legacyFormat, forceXml: forceXml, twentyFourSevenOnly: twentyFourSevenOnly).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     Gets taxis and minicabs contact information
     
     - parameter lat: (query) Latitude 
     - parameter lon: (query) Longitude 
     - parameter optype: (query) Operator Type e.g Minicab, Executive, Limousine (optional)
     - parameter wc: (query) Wheelchair accessible (optional)
     - parameter radius: (query) The radius of the bounding circle in metres (optional)
     - parameter name: (query) Trading name of operating company (optional)
     - parameter maxResults: (query) An optional parameter to limit the number of results return. Default and maximum is 20. (optional)
     - parameter legacyFormat: (query) Legacy Format (optional)
     - parameter forceXml: (query) Force Xml (optional)
     - parameter twentyFourSevenOnly: (query) Twenty Four Seven Only (optional)
     - returns: Observable<Object>
     */
    open class func cabwiseGet(lat: Double, lon: Double, optype: String? = nil, wc: String? = nil, radius: Double? = nil, name: String? = nil, maxResults: Int32? = nil, legacyFormat: Bool? = nil, forceXml: Bool? = nil, twentyFourSevenOnly: Bool? = nil) -> Observable<Object> {
        return Observable.create { observer -> Disposable in
            cabwiseGet(lat: lat, lon: lon, optype: optype, wc: wc, radius: radius, name: name, maxResults: maxResults, legacyFormat: legacyFormat, forceXml: forceXml, twentyFourSevenOnly: twentyFourSevenOnly) { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     Gets taxis and minicabs contact information
     - GET /Cabwise/search
     - examples: [{contentType=application/json, example={ }}, {contentType=application/xml, example=<null>
</null>}]
     - examples: [{contentType=application/json, example={ }}, {contentType=application/xml, example=<null>
</null>}]
     
     - parameter lat: (query) Latitude 
     - parameter lon: (query) Longitude 
     - parameter optype: (query) Operator Type e.g Minicab, Executive, Limousine (optional)
     - parameter wc: (query) Wheelchair accessible (optional)
     - parameter radius: (query) The radius of the bounding circle in metres (optional)
     - parameter name: (query) Trading name of operating company (optional)
     - parameter maxResults: (query) An optional parameter to limit the number of results return. Default and maximum is 20. (optional)
     - parameter legacyFormat: (query) Legacy Format (optional)
     - parameter forceXml: (query) Force Xml (optional)
     - parameter twentyFourSevenOnly: (query) Twenty Four Seven Only (optional)

     - returns: RequestBuilder<Object> 
     */
    open class func cabwiseGetWithRequestBuilder(lat: Double, lon: Double, optype: String? = nil, wc: String? = nil, radius: Double? = nil, name: String? = nil, maxResults: Int32? = nil, legacyFormat: Bool? = nil, forceXml: Bool? = nil, twentyFourSevenOnly: Bool? = nil) -> RequestBuilder<Object> {
        let path = "/Cabwise/search"
        let URLString = RxTfLAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "lat": lat, 
            "lon": lon, 
            "optype": optype, 
            "wc": wc, 
            "radius": radius, 
            "name": name, 
            "maxResults": maxResults?.encodeToJSON(), 
            "legacyFormat": legacyFormat, 
            "forceXml": forceXml, 
            "twentyFourSevenOnly": twentyFourSevenOnly
        ])
        

        let requestBuilder: RequestBuilder<Object>.Type = RxTfLAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
