//
// RoadAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire
import RxSwift



open class RoadAPI: APIBase {
    /**
     Gets a list of disrupted streets. If no date filters are provided, current disruptions are returned.
     
     - parameter startDate: (query) Optional, the start time to filter on. 
     - parameter endDate: (query) Optional, The end time to filter on. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func roadDisruptedStreets(startDate: Date, endDate: Date, completion: @escaping ((_ data: Object?,_ error: Error?) -> Void)) {
        roadDisruptedStreetsWithRequestBuilder(startDate: startDate, endDate: endDate).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     Gets a list of disrupted streets. If no date filters are provided, current disruptions are returned.
     
     - parameter startDate: (query) Optional, the start time to filter on. 
     - parameter endDate: (query) Optional, The end time to filter on. 
     - returns: Observable<Object>
     */
    open class func roadDisruptedStreets(startDate: Date, endDate: Date) -> Observable<Object> {
        return Observable.create { observer -> Disposable in
            roadDisruptedStreets(startDate: startDate, endDate: endDate) { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     Gets a list of disrupted streets. If no date filters are provided, current disruptions are returned.
     - GET /Road/all/Street/Disruption
     - examples: [{contentType=application/json, example={ }}, {contentType=application/xml, example=<null>
</null>}]
     - examples: [{contentType=application/json, example={ }}, {contentType=application/xml, example=<null>
</null>}]
     
     - parameter startDate: (query) Optional, the start time to filter on. 
     - parameter endDate: (query) Optional, The end time to filter on. 

     - returns: RequestBuilder<Object> 
     */
    open class func roadDisruptedStreetsWithRequestBuilder(startDate: Date, endDate: Date) -> RequestBuilder<Object> {
        let path = "/Road/all/Street/Disruption"
        let URLString = RxTfLAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "startDate": startDate.encodeToJSON(), 
            "endDate": endDate.encodeToJSON()
        ])
        

        let requestBuilder: RequestBuilder<Object>.Type = RxTfLAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get active disruptions, filtered by road ids
     
     - parameter ids: (path) Comma-separated list of road identifiers e.g. \&quot;A406, A2\&quot; use all for all to ignore id filter (a full list of supported road identifiers can be found at the /Road/ endpoint) 
     - parameter stripContent: (query) Optional, defaults to false. When true, removes every property/node except for id, point, severity, severityDescription, startDate, endDate, corridor details, location, comments and streets (optional)
     - parameter severities: (query) an optional list of Severity names to filter on (a valid list of severities can be obtained from the /Road/Meta/severities endpoint) (optional)
     - parameter categories: (query) an optional list of category names to filter on (a valid list of categories can be obtained from the /Road/Meta/categories endpoint) (optional)
     - parameter closures: (query) Optional, defaults to true. When true, always includes disruptions that have road closures, regardless of the severity filter. When false, the severity filter works as normal. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func roadDisruption(ids: [String], stripContent: Bool? = nil, severities: [String]? = nil, categories: [String]? = nil, closures: Bool? = nil, completion: @escaping ((_ data: [RoadDisruption]?,_ error: Error?) -> Void)) {
        roadDisruptionWithRequestBuilder(ids: ids, stripContent: stripContent, severities: severities, categories: categories, closures: closures).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     Get active disruptions, filtered by road ids
     
     - parameter ids: (path) Comma-separated list of road identifiers e.g. \&quot;A406, A2\&quot; use all for all to ignore id filter (a full list of supported road identifiers can be found at the /Road/ endpoint) 
     - parameter stripContent: (query) Optional, defaults to false. When true, removes every property/node except for id, point, severity, severityDescription, startDate, endDate, corridor details, location, comments and streets (optional)
     - parameter severities: (query) an optional list of Severity names to filter on (a valid list of severities can be obtained from the /Road/Meta/severities endpoint) (optional)
     - parameter categories: (query) an optional list of category names to filter on (a valid list of categories can be obtained from the /Road/Meta/categories endpoint) (optional)
     - parameter closures: (query) Optional, defaults to true. When true, always includes disruptions that have road closures, regardless of the severity filter. When false, the severity filter works as normal. (optional)
     - returns: Observable<[RoadDisruption]>
     */
    open class func roadDisruption(ids: [String], stripContent: Bool? = nil, severities: [String]? = nil, categories: [String]? = nil, closures: Bool? = nil) -> Observable<[RoadDisruption]> {
        return Observable.create { observer -> Disposable in
            roadDisruption(ids: ids, stripContent: stripContent, severities: severities, categories: categories, closures: closures) { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     Get active disruptions, filtered by road ids
     - GET /Road/{ids}/Disruption
     - examples: [{contentType=application/json, example=[ {
  "subCategory" : "aeiou",
  "corridorIds" : [ "aeiou" ],
  "currentUpdate" : "aeiou",
  "lastModifiedTime" : "2000-01-23T04:56:07.000+00:00",
  "streets" : [ {
    "directions" : "aeiou",
    "sourceSystemId" : 123456789,
    "sourceSystemKey" : "aeiou",
    "name" : "aeiou",
    "closure" : "aeiou",
    "segments" : [ {
      "toid" : "aeiou",
      "sourceSystemId" : 123456789,
      "sourceSystemKey" : "aeiou",
      "lineString" : "aeiou"
    } ]
  } ],
  "roadProject" : {
    "consultationStartDate" : "2000-01-23T04:56:07.000+00:00",
    "constructionStartDate" : "2000-01-23T04:56:07.000+00:00",
    "phase" : "aeiou",
    "projectPageUrl" : "aeiou",
    "consultationEndDate" : "2000-01-23T04:56:07.000+00:00",
    "cycleSuperhighwayId" : "aeiou",
    "contactEmail" : "aeiou",
    "consultationPageUrl" : "aeiou",
    "contactName" : "aeiou",
    "schemeName" : "aeiou",
    "projectSummaryPageUrl" : "aeiou",
    "externalPageUrl" : "aeiou",
    "boroughsBenefited" : [ "aeiou" ],
    "projectDescription" : "aeiou",
    "constructionEndDate" : "2000-01-23T04:56:07.000+00:00",
    "projectName" : "aeiou",
    "projectId" : "aeiou"
  },
  "recurringSchedules" : [ {
    "startTime" : "2000-01-23T04:56:07.000+00:00",
    "endTime" : "2000-01-23T04:56:07.000+00:00"
  } ],
  "currentUpdateDateTime" : "2000-01-23T04:56:07.000+00:00",
  "point" : "aeiou",
  "publishStartDate" : "2000-01-23T04:56:07.000+00:00",
  "levelOfInterest" : "aeiou",
  "geography" : {
    "geography" : {
      "wellKnownBinary" : "",
      "coordinateSystemId" : 123,
      "wellKnownText" : "aeiou"
    }
  },
  "linkUrl" : "aeiou",
  "id" : "aeiou",
  "severity" : "aeiou",
  "comments" : "aeiou",
  "isProvisional" : true,
  "linkText" : "aeiou",
  "endDateTime" : "2000-01-23T04:56:07.000+00:00",
  "hasClosures" : true,
  "url" : "aeiou",
  "timeFrame" : "aeiou",
  "roadDisruptionLines" : [ {
    "isDiversion" : true,
    "multiLineString" : "",
    "endDate" : "2000-01-23T04:56:07.000+00:00",
    "startTime" : "aeiou",
    "id" : 123,
    "roadDisruptionId" : "aeiou",
    "endTime" : "aeiou",
    "startDate" : "2000-01-23T04:56:07.000+00:00"
  } ],
  "startDateTime" : "2000-01-23T04:56:07.000+00:00",
  "roadDisruptionImpactAreas" : [ {
    "polygon" : "",
    "endDate" : "2000-01-23T04:56:07.000+00:00",
    "startTime" : "aeiou",
    "id" : 123,
    "roadDisruptionId" : "aeiou",
    "endTime" : "aeiou",
    "startDate" : "2000-01-23T04:56:07.000+00:00"
  } ],
  "publishEndDate" : "2000-01-23T04:56:07.000+00:00",
  "location" : "aeiou",
  "geometry" : "",
  "category" : "aeiou",
  "ordinal" : 123,
  "status" : "aeiou"
} ]}, {contentType=application/xml, example=<null>
  <id>aeiou</id>
  <url>aeiou</url>
  <point>aeiou</point>
  <severity>aeiou</severity>
  <ordinal>123</ordinal>
  <category>aeiou</category>
  <subCategory>aeiou</subCategory>
  <comments>aeiou</comments>
  <currentUpdate>aeiou</currentUpdate>
  <currentUpdateDateTime>2000-01-23T04:56:07.000Z</currentUpdateDateTime>
  <corridorIds>aeiou</corridorIds>
  <startDateTime>2000-01-23T04:56:07.000Z</startDateTime>
  <endDateTime>2000-01-23T04:56:07.000Z</endDateTime>
  <lastModifiedTime>2000-01-23T04:56:07.000Z</lastModifiedTime>
  <levelOfInterest>aeiou</levelOfInterest>
  <location>aeiou</location>
  <status>aeiou</status>
  <isProvisional>true</isProvisional>
  <hasClosures>true</hasClosures>
  <linkText>aeiou</linkText>
  <linkUrl>aeiou</linkUrl>
  <publishStartDate>2000-01-23T04:56:07.000Z</publishStartDate>
  <publishEndDate>2000-01-23T04:56:07.000Z</publishEndDate>
  <timeFrame>aeiou</timeFrame>
</null>}]
     - examples: [{contentType=application/json, example=[ {
  "subCategory" : "aeiou",
  "corridorIds" : [ "aeiou" ],
  "currentUpdate" : "aeiou",
  "lastModifiedTime" : "2000-01-23T04:56:07.000+00:00",
  "streets" : [ {
    "directions" : "aeiou",
    "sourceSystemId" : 123456789,
    "sourceSystemKey" : "aeiou",
    "name" : "aeiou",
    "closure" : "aeiou",
    "segments" : [ {
      "toid" : "aeiou",
      "sourceSystemId" : 123456789,
      "sourceSystemKey" : "aeiou",
      "lineString" : "aeiou"
    } ]
  } ],
  "roadProject" : {
    "consultationStartDate" : "2000-01-23T04:56:07.000+00:00",
    "constructionStartDate" : "2000-01-23T04:56:07.000+00:00",
    "phase" : "aeiou",
    "projectPageUrl" : "aeiou",
    "consultationEndDate" : "2000-01-23T04:56:07.000+00:00",
    "cycleSuperhighwayId" : "aeiou",
    "contactEmail" : "aeiou",
    "consultationPageUrl" : "aeiou",
    "contactName" : "aeiou",
    "schemeName" : "aeiou",
    "projectSummaryPageUrl" : "aeiou",
    "externalPageUrl" : "aeiou",
    "boroughsBenefited" : [ "aeiou" ],
    "projectDescription" : "aeiou",
    "constructionEndDate" : "2000-01-23T04:56:07.000+00:00",
    "projectName" : "aeiou",
    "projectId" : "aeiou"
  },
  "recurringSchedules" : [ {
    "startTime" : "2000-01-23T04:56:07.000+00:00",
    "endTime" : "2000-01-23T04:56:07.000+00:00"
  } ],
  "currentUpdateDateTime" : "2000-01-23T04:56:07.000+00:00",
  "point" : "aeiou",
  "publishStartDate" : "2000-01-23T04:56:07.000+00:00",
  "levelOfInterest" : "aeiou",
  "geography" : {
    "geography" : {
      "wellKnownBinary" : "",
      "coordinateSystemId" : 123,
      "wellKnownText" : "aeiou"
    }
  },
  "linkUrl" : "aeiou",
  "id" : "aeiou",
  "severity" : "aeiou",
  "comments" : "aeiou",
  "isProvisional" : true,
  "linkText" : "aeiou",
  "endDateTime" : "2000-01-23T04:56:07.000+00:00",
  "hasClosures" : true,
  "url" : "aeiou",
  "timeFrame" : "aeiou",
  "roadDisruptionLines" : [ {
    "isDiversion" : true,
    "multiLineString" : "",
    "endDate" : "2000-01-23T04:56:07.000+00:00",
    "startTime" : "aeiou",
    "id" : 123,
    "roadDisruptionId" : "aeiou",
    "endTime" : "aeiou",
    "startDate" : "2000-01-23T04:56:07.000+00:00"
  } ],
  "startDateTime" : "2000-01-23T04:56:07.000+00:00",
  "roadDisruptionImpactAreas" : [ {
    "polygon" : "",
    "endDate" : "2000-01-23T04:56:07.000+00:00",
    "startTime" : "aeiou",
    "id" : 123,
    "roadDisruptionId" : "aeiou",
    "endTime" : "aeiou",
    "startDate" : "2000-01-23T04:56:07.000+00:00"
  } ],
  "publishEndDate" : "2000-01-23T04:56:07.000+00:00",
  "location" : "aeiou",
  "geometry" : "",
  "category" : "aeiou",
  "ordinal" : 123,
  "status" : "aeiou"
} ]}, {contentType=application/xml, example=<null>
  <id>aeiou</id>
  <url>aeiou</url>
  <point>aeiou</point>
  <severity>aeiou</severity>
  <ordinal>123</ordinal>
  <category>aeiou</category>
  <subCategory>aeiou</subCategory>
  <comments>aeiou</comments>
  <currentUpdate>aeiou</currentUpdate>
  <currentUpdateDateTime>2000-01-23T04:56:07.000Z</currentUpdateDateTime>
  <corridorIds>aeiou</corridorIds>
  <startDateTime>2000-01-23T04:56:07.000Z</startDateTime>
  <endDateTime>2000-01-23T04:56:07.000Z</endDateTime>
  <lastModifiedTime>2000-01-23T04:56:07.000Z</lastModifiedTime>
  <levelOfInterest>aeiou</levelOfInterest>
  <location>aeiou</location>
  <status>aeiou</status>
  <isProvisional>true</isProvisional>
  <hasClosures>true</hasClosures>
  <linkText>aeiou</linkText>
  <linkUrl>aeiou</linkUrl>
  <publishStartDate>2000-01-23T04:56:07.000Z</publishStartDate>
  <publishEndDate>2000-01-23T04:56:07.000Z</publishEndDate>
  <timeFrame>aeiou</timeFrame>
</null>}]
     
     - parameter ids: (path) Comma-separated list of road identifiers e.g. \&quot;A406, A2\&quot; use all for all to ignore id filter (a full list of supported road identifiers can be found at the /Road/ endpoint) 
     - parameter stripContent: (query) Optional, defaults to false. When true, removes every property/node except for id, point, severity, severityDescription, startDate, endDate, corridor details, location, comments and streets (optional)
     - parameter severities: (query) an optional list of Severity names to filter on (a valid list of severities can be obtained from the /Road/Meta/severities endpoint) (optional)
     - parameter categories: (query) an optional list of category names to filter on (a valid list of categories can be obtained from the /Road/Meta/categories endpoint) (optional)
     - parameter closures: (query) Optional, defaults to true. When true, always includes disruptions that have road closures, regardless of the severity filter. When false, the severity filter works as normal. (optional)

     - returns: RequestBuilder<[RoadDisruption]> 
     */
    open class func roadDisruptionWithRequestBuilder(ids: [String], stripContent: Bool? = nil, severities: [String]? = nil, categories: [String]? = nil, closures: Bool? = nil) -> RequestBuilder<[RoadDisruption]> {
        var path = "/Road/{ids}/Disruption"
        path = path.replacingOccurrences(of: "{ids}", with: ids.asParameter, options: .literal, range: nil)
        let URLString = RxTfLAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "stripContent": stripContent, 
            "severities": severities, 
            "categories": categories, 
            "closures": closures
        ])
        

        let requestBuilder: RequestBuilder<[RoadDisruption]>.Type = RxTfLAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Gets a list of active disruptions filtered by disruption Ids.
     
     - parameter disruptionIds: (path) Comma-separated list of disruption identifiers to filter by. 
     - parameter stripContent: (query) Optional, defaults to false. When true, removes every property/node except for id, point, severity, severityDescription, startDate, endDate, corridor details, location and comments. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func roadDisruptionById(disruptionIds: [String], stripContent: Bool? = nil, completion: @escaping ((_ data: RoadDisruption?,_ error: Error?) -> Void)) {
        roadDisruptionByIdWithRequestBuilder(disruptionIds: disruptionIds, stripContent: stripContent).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     Gets a list of active disruptions filtered by disruption Ids.
     
     - parameter disruptionIds: (path) Comma-separated list of disruption identifiers to filter by. 
     - parameter stripContent: (query) Optional, defaults to false. When true, removes every property/node except for id, point, severity, severityDescription, startDate, endDate, corridor details, location and comments. (optional)
     - returns: Observable<RoadDisruption>
     */
    open class func roadDisruptionById(disruptionIds: [String], stripContent: Bool? = nil) -> Observable<RoadDisruption> {
        return Observable.create { observer -> Disposable in
            roadDisruptionById(disruptionIds: disruptionIds, stripContent: stripContent) { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     Gets a list of active disruptions filtered by disruption Ids.
     - GET /Road/all/Disruption/{disruptionIds}
     - examples: [{contentType=application/json, example={
  "subCategory" : "aeiou",
  "corridorIds" : [ "aeiou" ],
  "currentUpdate" : "aeiou",
  "lastModifiedTime" : "2000-01-23T04:56:07.000+00:00",
  "streets" : [ {
    "directions" : "aeiou",
    "sourceSystemId" : 123456789,
    "sourceSystemKey" : "aeiou",
    "name" : "aeiou",
    "closure" : "aeiou",
    "segments" : [ {
      "toid" : "aeiou",
      "sourceSystemId" : 123456789,
      "sourceSystemKey" : "aeiou",
      "lineString" : "aeiou"
    } ]
  } ],
  "roadProject" : {
    "consultationStartDate" : "2000-01-23T04:56:07.000+00:00",
    "constructionStartDate" : "2000-01-23T04:56:07.000+00:00",
    "phase" : "aeiou",
    "projectPageUrl" : "aeiou",
    "consultationEndDate" : "2000-01-23T04:56:07.000+00:00",
    "cycleSuperhighwayId" : "aeiou",
    "contactEmail" : "aeiou",
    "consultationPageUrl" : "aeiou",
    "contactName" : "aeiou",
    "schemeName" : "aeiou",
    "projectSummaryPageUrl" : "aeiou",
    "externalPageUrl" : "aeiou",
    "boroughsBenefited" : [ "aeiou" ],
    "projectDescription" : "aeiou",
    "constructionEndDate" : "2000-01-23T04:56:07.000+00:00",
    "projectName" : "aeiou",
    "projectId" : "aeiou"
  },
  "recurringSchedules" : [ {
    "startTime" : "2000-01-23T04:56:07.000+00:00",
    "endTime" : "2000-01-23T04:56:07.000+00:00"
  } ],
  "currentUpdateDateTime" : "2000-01-23T04:56:07.000+00:00",
  "point" : "aeiou",
  "publishStartDate" : "2000-01-23T04:56:07.000+00:00",
  "levelOfInterest" : "aeiou",
  "geography" : {
    "geography" : {
      "wellKnownBinary" : "",
      "coordinateSystemId" : 123,
      "wellKnownText" : "aeiou"
    }
  },
  "linkUrl" : "aeiou",
  "id" : "aeiou",
  "severity" : "aeiou",
  "comments" : "aeiou",
  "isProvisional" : true,
  "linkText" : "aeiou",
  "endDateTime" : "2000-01-23T04:56:07.000+00:00",
  "hasClosures" : true,
  "url" : "aeiou",
  "timeFrame" : "aeiou",
  "roadDisruptionLines" : [ {
    "isDiversion" : true,
    "multiLineString" : "",
    "endDate" : "2000-01-23T04:56:07.000+00:00",
    "startTime" : "aeiou",
    "id" : 123,
    "roadDisruptionId" : "aeiou",
    "endTime" : "aeiou",
    "startDate" : "2000-01-23T04:56:07.000+00:00"
  } ],
  "startDateTime" : "2000-01-23T04:56:07.000+00:00",
  "roadDisruptionImpactAreas" : [ {
    "polygon" : "",
    "endDate" : "2000-01-23T04:56:07.000+00:00",
    "startTime" : "aeiou",
    "id" : 123,
    "roadDisruptionId" : "aeiou",
    "endTime" : "aeiou",
    "startDate" : "2000-01-23T04:56:07.000+00:00"
  } ],
  "publishEndDate" : "2000-01-23T04:56:07.000+00:00",
  "location" : "aeiou",
  "geometry" : "",
  "category" : "aeiou",
  "ordinal" : 123,
  "status" : "aeiou"
}}, {contentType=application/xml, example=<null>
  <id>aeiou</id>
  <url>aeiou</url>
  <point>aeiou</point>
  <severity>aeiou</severity>
  <ordinal>123</ordinal>
  <category>aeiou</category>
  <subCategory>aeiou</subCategory>
  <comments>aeiou</comments>
  <currentUpdate>aeiou</currentUpdate>
  <currentUpdateDateTime>2000-01-23T04:56:07.000Z</currentUpdateDateTime>
  <corridorIds>aeiou</corridorIds>
  <startDateTime>2000-01-23T04:56:07.000Z</startDateTime>
  <endDateTime>2000-01-23T04:56:07.000Z</endDateTime>
  <lastModifiedTime>2000-01-23T04:56:07.000Z</lastModifiedTime>
  <levelOfInterest>aeiou</levelOfInterest>
  <location>aeiou</location>
  <status>aeiou</status>
  <isProvisional>true</isProvisional>
  <hasClosures>true</hasClosures>
  <linkText>aeiou</linkText>
  <linkUrl>aeiou</linkUrl>
  <publishStartDate>2000-01-23T04:56:07.000Z</publishStartDate>
  <publishEndDate>2000-01-23T04:56:07.000Z</publishEndDate>
  <timeFrame>aeiou</timeFrame>
</null>}]
     - examples: [{contentType=application/json, example={
  "subCategory" : "aeiou",
  "corridorIds" : [ "aeiou" ],
  "currentUpdate" : "aeiou",
  "lastModifiedTime" : "2000-01-23T04:56:07.000+00:00",
  "streets" : [ {
    "directions" : "aeiou",
    "sourceSystemId" : 123456789,
    "sourceSystemKey" : "aeiou",
    "name" : "aeiou",
    "closure" : "aeiou",
    "segments" : [ {
      "toid" : "aeiou",
      "sourceSystemId" : 123456789,
      "sourceSystemKey" : "aeiou",
      "lineString" : "aeiou"
    } ]
  } ],
  "roadProject" : {
    "consultationStartDate" : "2000-01-23T04:56:07.000+00:00",
    "constructionStartDate" : "2000-01-23T04:56:07.000+00:00",
    "phase" : "aeiou",
    "projectPageUrl" : "aeiou",
    "consultationEndDate" : "2000-01-23T04:56:07.000+00:00",
    "cycleSuperhighwayId" : "aeiou",
    "contactEmail" : "aeiou",
    "consultationPageUrl" : "aeiou",
    "contactName" : "aeiou",
    "schemeName" : "aeiou",
    "projectSummaryPageUrl" : "aeiou",
    "externalPageUrl" : "aeiou",
    "boroughsBenefited" : [ "aeiou" ],
    "projectDescription" : "aeiou",
    "constructionEndDate" : "2000-01-23T04:56:07.000+00:00",
    "projectName" : "aeiou",
    "projectId" : "aeiou"
  },
  "recurringSchedules" : [ {
    "startTime" : "2000-01-23T04:56:07.000+00:00",
    "endTime" : "2000-01-23T04:56:07.000+00:00"
  } ],
  "currentUpdateDateTime" : "2000-01-23T04:56:07.000+00:00",
  "point" : "aeiou",
  "publishStartDate" : "2000-01-23T04:56:07.000+00:00",
  "levelOfInterest" : "aeiou",
  "geography" : {
    "geography" : {
      "wellKnownBinary" : "",
      "coordinateSystemId" : 123,
      "wellKnownText" : "aeiou"
    }
  },
  "linkUrl" : "aeiou",
  "id" : "aeiou",
  "severity" : "aeiou",
  "comments" : "aeiou",
  "isProvisional" : true,
  "linkText" : "aeiou",
  "endDateTime" : "2000-01-23T04:56:07.000+00:00",
  "hasClosures" : true,
  "url" : "aeiou",
  "timeFrame" : "aeiou",
  "roadDisruptionLines" : [ {
    "isDiversion" : true,
    "multiLineString" : "",
    "endDate" : "2000-01-23T04:56:07.000+00:00",
    "startTime" : "aeiou",
    "id" : 123,
    "roadDisruptionId" : "aeiou",
    "endTime" : "aeiou",
    "startDate" : "2000-01-23T04:56:07.000+00:00"
  } ],
  "startDateTime" : "2000-01-23T04:56:07.000+00:00",
  "roadDisruptionImpactAreas" : [ {
    "polygon" : "",
    "endDate" : "2000-01-23T04:56:07.000+00:00",
    "startTime" : "aeiou",
    "id" : 123,
    "roadDisruptionId" : "aeiou",
    "endTime" : "aeiou",
    "startDate" : "2000-01-23T04:56:07.000+00:00"
  } ],
  "publishEndDate" : "2000-01-23T04:56:07.000+00:00",
  "location" : "aeiou",
  "geometry" : "",
  "category" : "aeiou",
  "ordinal" : 123,
  "status" : "aeiou"
}}, {contentType=application/xml, example=<null>
  <id>aeiou</id>
  <url>aeiou</url>
  <point>aeiou</point>
  <severity>aeiou</severity>
  <ordinal>123</ordinal>
  <category>aeiou</category>
  <subCategory>aeiou</subCategory>
  <comments>aeiou</comments>
  <currentUpdate>aeiou</currentUpdate>
  <currentUpdateDateTime>2000-01-23T04:56:07.000Z</currentUpdateDateTime>
  <corridorIds>aeiou</corridorIds>
  <startDateTime>2000-01-23T04:56:07.000Z</startDateTime>
  <endDateTime>2000-01-23T04:56:07.000Z</endDateTime>
  <lastModifiedTime>2000-01-23T04:56:07.000Z</lastModifiedTime>
  <levelOfInterest>aeiou</levelOfInterest>
  <location>aeiou</location>
  <status>aeiou</status>
  <isProvisional>true</isProvisional>
  <hasClosures>true</hasClosures>
  <linkText>aeiou</linkText>
  <linkUrl>aeiou</linkUrl>
  <publishStartDate>2000-01-23T04:56:07.000Z</publishStartDate>
  <publishEndDate>2000-01-23T04:56:07.000Z</publishEndDate>
  <timeFrame>aeiou</timeFrame>
</null>}]
     
     - parameter disruptionIds: (path) Comma-separated list of disruption identifiers to filter by. 
     - parameter stripContent: (query) Optional, defaults to false. When true, removes every property/node except for id, point, severity, severityDescription, startDate, endDate, corridor details, location and comments. (optional)

     - returns: RequestBuilder<RoadDisruption> 
     */
    open class func roadDisruptionByIdWithRequestBuilder(disruptionIds: [String], stripContent: Bool? = nil) -> RequestBuilder<RoadDisruption> {
        var path = "/Road/all/Disruption/{disruptionIds}"
        path = path.replacingOccurrences(of: "{disruptionIds}", with: disruptionIds.asParameter, options: .literal, range: nil)
        let URLString = RxTfLAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "stripContent": stripContent
        ])
        

        let requestBuilder: RequestBuilder<RoadDisruption>.Type = RxTfLAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Gets all roads managed by TfL
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func roadGet(completion: @escaping ((_ data: [RoadCorridor]?,_ error: Error?) -> Void)) {
        roadGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     Gets all roads managed by TfL
     
     - returns: Observable<[RoadCorridor]>
     */
    open class func roadGet() -> Observable<[RoadCorridor]> {
        return Observable.create { observer -> Disposable in
            roadGet() { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     Gets all roads managed by TfL
     - GET /Road
     - examples: [{contentType=application/json, example=[ {
  "statusSeverityDescription" : "aeiou",
  "envelope" : "aeiou",
  "statusAggregationEndDate" : "2000-01-23T04:56:07.000+00:00",
  "statusAggregationStartDate" : "2000-01-23T04:56:07.000+00:00",
  "displayName" : "aeiou",
  "statusSeverity" : "aeiou",
  "bounds" : "aeiou",
  "id" : "aeiou",
  "url" : "aeiou",
  "group" : "aeiou"
} ]}, {contentType=application/xml, example=<null>
  <id>aeiou</id>
  <displayName>aeiou</displayName>
  <group>aeiou</group>
  <statusSeverity>aeiou</statusSeverity>
  <statusSeverityDescription>aeiou</statusSeverityDescription>
  <bounds>aeiou</bounds>
  <envelope>aeiou</envelope>
  <statusAggregationStartDate>2000-01-23T04:56:07.000Z</statusAggregationStartDate>
  <statusAggregationEndDate>2000-01-23T04:56:07.000Z</statusAggregationEndDate>
  <url>aeiou</url>
</null>}]
     - examples: [{contentType=application/json, example=[ {
  "statusSeverityDescription" : "aeiou",
  "envelope" : "aeiou",
  "statusAggregationEndDate" : "2000-01-23T04:56:07.000+00:00",
  "statusAggregationStartDate" : "2000-01-23T04:56:07.000+00:00",
  "displayName" : "aeiou",
  "statusSeverity" : "aeiou",
  "bounds" : "aeiou",
  "id" : "aeiou",
  "url" : "aeiou",
  "group" : "aeiou"
} ]}, {contentType=application/xml, example=<null>
  <id>aeiou</id>
  <displayName>aeiou</displayName>
  <group>aeiou</group>
  <statusSeverity>aeiou</statusSeverity>
  <statusSeverityDescription>aeiou</statusSeverityDescription>
  <bounds>aeiou</bounds>
  <envelope>aeiou</envelope>
  <statusAggregationStartDate>2000-01-23T04:56:07.000Z</statusAggregationStartDate>
  <statusAggregationEndDate>2000-01-23T04:56:07.000Z</statusAggregationEndDate>
  <url>aeiou</url>
</null>}]

     - returns: RequestBuilder<[RoadCorridor]> 
     */
    open class func roadGetWithRequestBuilder() -> RequestBuilder<[RoadCorridor]> {
        let path = "/Road"
        let URLString = RxTfLAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[RoadCorridor]>.Type = RxTfLAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Gets the road with the specified id (e.g. A1)
     
     - parameter ids: (path) Comma-separated list of road identifiers e.g. \&quot;A406, A2\&quot; (a full list of supported road identifiers can be found at the /Road/ endpoint) 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func roadGet_0(ids: [String], completion: @escaping ((_ data: [RoadCorridor]?,_ error: Error?) -> Void)) {
        roadGet_0WithRequestBuilder(ids: ids).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     Gets the road with the specified id (e.g. A1)
     
     - parameter ids: (path) Comma-separated list of road identifiers e.g. \&quot;A406, A2\&quot; (a full list of supported road identifiers can be found at the /Road/ endpoint) 
     - returns: Observable<[RoadCorridor]>
     */
    open class func roadGet_0(ids: [String]) -> Observable<[RoadCorridor]> {
        return Observable.create { observer -> Disposable in
            roadGet_0(ids: ids) { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     Gets the road with the specified id (e.g. A1)
     - GET /Road/{ids}
     - examples: [{contentType=application/json, example=[ {
  "statusSeverityDescription" : "aeiou",
  "envelope" : "aeiou",
  "statusAggregationEndDate" : "2000-01-23T04:56:07.000+00:00",
  "statusAggregationStartDate" : "2000-01-23T04:56:07.000+00:00",
  "displayName" : "aeiou",
  "statusSeverity" : "aeiou",
  "bounds" : "aeiou",
  "id" : "aeiou",
  "url" : "aeiou",
  "group" : "aeiou"
} ]}, {contentType=application/xml, example=<null>
  <id>aeiou</id>
  <displayName>aeiou</displayName>
  <group>aeiou</group>
  <statusSeverity>aeiou</statusSeverity>
  <statusSeverityDescription>aeiou</statusSeverityDescription>
  <bounds>aeiou</bounds>
  <envelope>aeiou</envelope>
  <statusAggregationStartDate>2000-01-23T04:56:07.000Z</statusAggregationStartDate>
  <statusAggregationEndDate>2000-01-23T04:56:07.000Z</statusAggregationEndDate>
  <url>aeiou</url>
</null>}]
     - examples: [{contentType=application/json, example=[ {
  "statusSeverityDescription" : "aeiou",
  "envelope" : "aeiou",
  "statusAggregationEndDate" : "2000-01-23T04:56:07.000+00:00",
  "statusAggregationStartDate" : "2000-01-23T04:56:07.000+00:00",
  "displayName" : "aeiou",
  "statusSeverity" : "aeiou",
  "bounds" : "aeiou",
  "id" : "aeiou",
  "url" : "aeiou",
  "group" : "aeiou"
} ]}, {contentType=application/xml, example=<null>
  <id>aeiou</id>
  <displayName>aeiou</displayName>
  <group>aeiou</group>
  <statusSeverity>aeiou</statusSeverity>
  <statusSeverityDescription>aeiou</statusSeverityDescription>
  <bounds>aeiou</bounds>
  <envelope>aeiou</envelope>
  <statusAggregationStartDate>2000-01-23T04:56:07.000Z</statusAggregationStartDate>
  <statusAggregationEndDate>2000-01-23T04:56:07.000Z</statusAggregationEndDate>
  <url>aeiou</url>
</null>}]
     
     - parameter ids: (path) Comma-separated list of road identifiers e.g. \&quot;A406, A2\&quot; (a full list of supported road identifiers can be found at the /Road/ endpoint) 

     - returns: RequestBuilder<[RoadCorridor]> 
     */
    open class func roadGet_0WithRequestBuilder(ids: [String]) -> RequestBuilder<[RoadCorridor]> {
        var path = "/Road/{ids}"
        path = path.replacingOccurrences(of: "{ids}", with: ids.asParameter, options: .literal, range: nil)
        let URLString = RxTfLAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[RoadCorridor]>.Type = RxTfLAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Gets a list of valid RoadDisruption categories
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func roadMetaCategories(completion: @escaping ((_ data: [String]?,_ error: Error?) -> Void)) {
        roadMetaCategoriesWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     Gets a list of valid RoadDisruption categories
     
     - returns: Observable<[String]>
     */
    open class func roadMetaCategories() -> Observable<[String]> {
        return Observable.create { observer -> Disposable in
            roadMetaCategories() { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     Gets a list of valid RoadDisruption categories
     - GET /Road/Meta/Categories
     - examples: [{contentType=application/json, example=[ "aeiou" ]}, {contentType=application/xml, example=aeiou}]
     - examples: [{contentType=application/json, example=[ "aeiou" ]}, {contentType=application/xml, example=aeiou}]

     - returns: RequestBuilder<[String]> 
     */
    open class func roadMetaCategoriesWithRequestBuilder() -> RequestBuilder<[String]> {
        let path = "/Road/Meta/Categories"
        let URLString = RxTfLAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[String]>.Type = RxTfLAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Gets a list of valid RoadDisruption severity codes
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func roadMetaSeverities(completion: @escaping ((_ data: [StatusSeverity]?,_ error: Error?) -> Void)) {
        roadMetaSeveritiesWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     Gets a list of valid RoadDisruption severity codes
     
     - returns: Observable<[StatusSeverity]>
     */
    open class func roadMetaSeverities() -> Observable<[StatusSeverity]> {
        return Observable.create { observer -> Disposable in
            roadMetaSeverities() { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     Gets a list of valid RoadDisruption severity codes
     - GET /Road/Meta/Severities
     - examples: [{contentType=application/json, example=[ {
  "severityLevel" : 123,
  "modeName" : "aeiou",
  "description" : "aeiou"
} ]}, {contentType=application/xml, example=<null>
  <modeName>aeiou</modeName>
  <severityLevel>123</severityLevel>
  <description>aeiou</description>
</null>}]
     - examples: [{contentType=application/json, example=[ {
  "severityLevel" : 123,
  "modeName" : "aeiou",
  "description" : "aeiou"
} ]}, {contentType=application/xml, example=<null>
  <modeName>aeiou</modeName>
  <severityLevel>123</severityLevel>
  <description>aeiou</description>
</null>}]

     - returns: RequestBuilder<[StatusSeverity]> 
     */
    open class func roadMetaSeveritiesWithRequestBuilder() -> RequestBuilder<[StatusSeverity]> {
        let path = "/Road/Meta/Severities"
        let URLString = RxTfLAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[StatusSeverity]>.Type = RxTfLAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Gets the specified roads with the status aggregated over the date range specified, or now until the end of today if no dates are passed.
     
     - parameter ids: (path) Comma-separated list of road identifiers e.g. \&quot;A406, A2\&quot; or use \&quot;all\&quot; to ignore id filter (a full list of supported road identifiers can be found at the /Road/ endpoint) 
     - parameter dateRangeNullableStartDate: (query)  (optional)
     - parameter dateRangeNullableEndDate: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func roadStatus(ids: [String], dateRangeNullableStartDate: Date? = nil, dateRangeNullableEndDate: Date? = nil, completion: @escaping ((_ data: [RoadCorridor]?,_ error: Error?) -> Void)) {
        roadStatusWithRequestBuilder(ids: ids, dateRangeNullableStartDate: dateRangeNullableStartDate, dateRangeNullableEndDate: dateRangeNullableEndDate).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     Gets the specified roads with the status aggregated over the date range specified, or now until the end of today if no dates are passed.
     
     - parameter ids: (path) Comma-separated list of road identifiers e.g. \&quot;A406, A2\&quot; or use \&quot;all\&quot; to ignore id filter (a full list of supported road identifiers can be found at the /Road/ endpoint) 
     - parameter dateRangeNullableStartDate: (query)  (optional)
     - parameter dateRangeNullableEndDate: (query)  (optional)
     - returns: Observable<[RoadCorridor]>
     */
    open class func roadStatus(ids: [String], dateRangeNullableStartDate: Date? = nil, dateRangeNullableEndDate: Date? = nil) -> Observable<[RoadCorridor]> {
        return Observable.create { observer -> Disposable in
            roadStatus(ids: ids, dateRangeNullableStartDate: dateRangeNullableStartDate, dateRangeNullableEndDate: dateRangeNullableEndDate) { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     Gets the specified roads with the status aggregated over the date range specified, or now until the end of today if no dates are passed.
     - GET /Road/{ids}/Status
     - examples: [{contentType=application/json, example=[ {
  "statusSeverityDescription" : "aeiou",
  "envelope" : "aeiou",
  "statusAggregationEndDate" : "2000-01-23T04:56:07.000+00:00",
  "statusAggregationStartDate" : "2000-01-23T04:56:07.000+00:00",
  "displayName" : "aeiou",
  "statusSeverity" : "aeiou",
  "bounds" : "aeiou",
  "id" : "aeiou",
  "url" : "aeiou",
  "group" : "aeiou"
} ]}, {contentType=application/xml, example=<null>
  <id>aeiou</id>
  <displayName>aeiou</displayName>
  <group>aeiou</group>
  <statusSeverity>aeiou</statusSeverity>
  <statusSeverityDescription>aeiou</statusSeverityDescription>
  <bounds>aeiou</bounds>
  <envelope>aeiou</envelope>
  <statusAggregationStartDate>2000-01-23T04:56:07.000Z</statusAggregationStartDate>
  <statusAggregationEndDate>2000-01-23T04:56:07.000Z</statusAggregationEndDate>
  <url>aeiou</url>
</null>}]
     - examples: [{contentType=application/json, example=[ {
  "statusSeverityDescription" : "aeiou",
  "envelope" : "aeiou",
  "statusAggregationEndDate" : "2000-01-23T04:56:07.000+00:00",
  "statusAggregationStartDate" : "2000-01-23T04:56:07.000+00:00",
  "displayName" : "aeiou",
  "statusSeverity" : "aeiou",
  "bounds" : "aeiou",
  "id" : "aeiou",
  "url" : "aeiou",
  "group" : "aeiou"
} ]}, {contentType=application/xml, example=<null>
  <id>aeiou</id>
  <displayName>aeiou</displayName>
  <group>aeiou</group>
  <statusSeverity>aeiou</statusSeverity>
  <statusSeverityDescription>aeiou</statusSeverityDescription>
  <bounds>aeiou</bounds>
  <envelope>aeiou</envelope>
  <statusAggregationStartDate>2000-01-23T04:56:07.000Z</statusAggregationStartDate>
  <statusAggregationEndDate>2000-01-23T04:56:07.000Z</statusAggregationEndDate>
  <url>aeiou</url>
</null>}]
     
     - parameter ids: (path) Comma-separated list of road identifiers e.g. \&quot;A406, A2\&quot; or use \&quot;all\&quot; to ignore id filter (a full list of supported road identifiers can be found at the /Road/ endpoint) 
     - parameter dateRangeNullableStartDate: (query)  (optional)
     - parameter dateRangeNullableEndDate: (query)  (optional)

     - returns: RequestBuilder<[RoadCorridor]> 
     */
    open class func roadStatusWithRequestBuilder(ids: [String], dateRangeNullableStartDate: Date? = nil, dateRangeNullableEndDate: Date? = nil) -> RequestBuilder<[RoadCorridor]> {
        var path = "/Road/{ids}/Status"
        path = path.replacingOccurrences(of: "{ids}", with: ids.asParameter, options: .literal, range: nil)
        let URLString = RxTfLAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "dateRangeNullable.startDate": dateRangeNullableStartDate?.encodeToJSON(), 
            "dateRangeNullable.endDate": dateRangeNullableEndDate?.encodeToJSON()
        ])
        

        let requestBuilder: RequestBuilder<[RoadCorridor]>.Type = RxTfLAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
