//
// ApiVersionInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ApiVersionInfo: JSONEncodable {

    public var label: String?
    public var timestamp: Date?
    public var version: String?
    public var assemblies: [String]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["label"] = self.label
        nillableDictionary["timestamp"] = self.timestamp?.encodeToJSON()
        nillableDictionary["version"] = self.version
        nillableDictionary["assemblies"] = self.assemblies?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
