//
// Bay.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Bay: JSONEncodable {

    public var bayType: String?
    public var bayCount: Int32?
    public var free: Int32?
    public var occupied: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["bayType"] = self.bayType
        nillableDictionary["bayCount"] = self.bayCount?.encodeToJSON()
        nillableDictionary["free"] = self.free?.encodeToJSON()
        nillableDictionary["occupied"] = self.occupied?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
