//
// Casualty.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Casualty: JSONEncodable {

    public var age: Int32?
    public var _class: String?
    public var severity: String?
    public var mode: String?
    public var ageBand: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["age"] = self.age?.encodeToJSON()
        nillableDictionary["class"] = self._class
        nillableDictionary["severity"] = self.severity
        nillableDictionary["mode"] = self.mode
        nillableDictionary["ageBand"] = self.ageBand

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
