//
// Coordinate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Coordinate: JSONEncodable {

    public var longitude: Double?
    public var latitude: Double?
    public var easting: Double?
    public var northing: Double?
    public var xCoord: Int32?
    public var yCoord: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["longitude"] = self.longitude
        nillableDictionary["latitude"] = self.latitude
        nillableDictionary["easting"] = self.easting
        nillableDictionary["northing"] = self.northing
        nillableDictionary["xCoord"] = self.xCoord?.encodeToJSON()
        nillableDictionary["yCoord"] = self.yCoord?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
