//
// Crowding.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Crowding: JSONEncodable {

    /** Busiest times at a station (static information) */
    public var passengerFlows: [PassengerFlow]?
    /** Train Loading on a scale 1-6, 1 being \&quot;Very quiet\&quot; and 6 being \&quot;Exceptionally busy\&quot; (static information) */
    public var trainLoadings: [TrainLoading]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["passengerFlows"] = self.passengerFlows?.encodeToJSON()
        nillableDictionary["trainLoadings"] = self.trainLoadings?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
