//
// Disruption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents a disruption to a route within the transport network. */
open class Disruption: JSONEncodable {

    public enum Category: String { 
        case undefined = "Undefined"
        case realTime = "RealTime"
        case plannedWork = "PlannedWork"
        case information = "Information"
        case event = "Event"
        case crowding = "Crowding"
        case statusAlert = "StatusAlert"
    }
    /** Gets or sets the category of this dispruption. */
    public var category: Category?
    /** Gets or sets the disruption type of this dispruption. */
    public var type: String?
    /** Gets or sets the description of the category. */
    public var categoryDescription: String?
    /** Gets or sets the description of this disruption. */
    public var description: String?
    /** Gets or sets the additionaInfo of this disruption. */
    public var additionalInfo: String?
    /** Gets or sets the date/time when this disruption was created. */
    public var created: Date?
    /** Gets or sets the date/time when this disruption was last updated. */
    public var lastUpdate: Date?
    /** Gets or sets the routes affected by this disruption */
    public var affectedRoutes: [RouteSection]?
    /** Gets or sets the stops affected by this disruption */
    public var affectedStops: [StopPoint]?
    public var isBlocking: Bool?
    public var isWholeLine: Bool?
    public var closureText: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["category"] = self.category?.rawValue
        nillableDictionary["type"] = self.type
        nillableDictionary["categoryDescription"] = self.categoryDescription
        nillableDictionary["description"] = self.description
        nillableDictionary["additionalInfo"] = self.additionalInfo
        nillableDictionary["created"] = self.created?.encodeToJSON()
        nillableDictionary["lastUpdate"] = self.lastUpdate?.encodeToJSON()
        nillableDictionary["affectedRoutes"] = self.affectedRoutes?.encodeToJSON()
        nillableDictionary["affectedStops"] = self.affectedStops?.encodeToJSON()
        nillableDictionary["isBlocking"] = self.isBlocking
        nillableDictionary["isWholeLine"] = self.isWholeLine
        nillableDictionary["closureText"] = self.closureText

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
