//
// EmissionsSurchargeVehicle.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/**  */
open class EmissionsSurchargeVehicle: JSONEncodable {

    public enum Compliance: String { 
        case notCompliant = "NotCompliant"
        case compliant = "Compliant"
        case exempt = "Exempt"
    }
    public var vrm: String?
    public var type: String?
    public var make: String?
    public var model: String?
    public var colour: String?
    public var compliance: Compliance?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["vrm"] = self.vrm
        nillableDictionary["type"] = self.type
        nillableDictionary["make"] = self.make
        nillableDictionary["model"] = self.model
        nillableDictionary["colour"] = self.colour
        nillableDictionary["compliance"] = self.compliance?.rawValue

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
