//
// Fare.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Fare: JSONEncodable {

    public var id: Int32?
    public var passengerType: String?
    public var validFrom: Date?
    public var validUntil: Date?
    public var ticketTime: String?
    public var ticketType: String?
    public var cost: String?
    public var cap: Double?
    public var description: String?
    public var zone: String?
    public var mode: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["passengerType"] = self.passengerType
        nillableDictionary["validFrom"] = self.validFrom?.encodeToJSON()
        nillableDictionary["validUntil"] = self.validUntil?.encodeToJSON()
        nillableDictionary["ticketTime"] = self.ticketTime
        nillableDictionary["ticketType"] = self.ticketType
        nillableDictionary["cost"] = self.cost
        nillableDictionary["cap"] = self.cap
        nillableDictionary["description"] = self.description
        nillableDictionary["zone"] = self.zone
        nillableDictionary["mode"] = self.mode

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
