//
// FareBounds.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class FareBounds: JSONEncodable {

    public var id: Int32?
    public var from: String?
    public var to: String?
    public var via: String?
    public var routeCode: String?
    public var description: String?
    public var displayName: String?
    public var _operator: String?
    public var displayOrder: Int32?
    public var isPopularFare: Bool?
    public var isPopularTravelCard: Bool?
    public var isTour: Bool?
    public var messages: [Message]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["from"] = self.from
        nillableDictionary["to"] = self.to
        nillableDictionary["via"] = self.via
        nillableDictionary["routeCode"] = self.routeCode
        nillableDictionary["description"] = self.description
        nillableDictionary["displayName"] = self.displayName
        nillableDictionary["operator"] = self._operator
        nillableDictionary["displayOrder"] = self.displayOrder?.encodeToJSON()
        nillableDictionary["isPopularFare"] = self.isPopularFare
        nillableDictionary["isPopularTravelCard"] = self.isPopularTravelCard
        nillableDictionary["isTour"] = self.isTour
        nillableDictionary["messages"] = self.messages?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
