//
// FaresPeriod.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class FaresPeriod: JSONEncodable {

    public var id: Int32?
    public var startDate: Date?
    public var viewableDate: Date?
    public var endDate: Date?
    public var isFuture: Bool?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["startDate"] = self.startDate?.encodeToJSON()
        nillableDictionary["viewableDate"] = self.viewableDate?.encodeToJSON()
        nillableDictionary["endDate"] = self.endDate?.encodeToJSON()
        nillableDictionary["isFuture"] = self.isFuture

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
