//
// FareDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class FareDetails: JSONEncodable {

    public var boundsId: Int32?
    public var startDate: Date?
    public var endDate: Date?
    public var mode: String?
    public var passengerType: String?
    public var from: String?
    public var to: String?
    public var fromStation: String?
    public var toStation: String?
    public var via: String?
    public var routeCode: String?
    public var displayName: String?
    public var displayOrder: Int32?
    public var routeDescription: String?
    public var validatorInformation: String?
    public var _operator: String?
    public var specialFare: Bool?
    public var throughFare: Bool?
    public var isTour: Bool?
    public var ticketsAvailable: [Ticket]?
    public var messages: [Message]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["boundsId"] = self.boundsId?.encodeToJSON()
        nillableDictionary["startDate"] = self.startDate?.encodeToJSON()
        nillableDictionary["endDate"] = self.endDate?.encodeToJSON()
        nillableDictionary["mode"] = self.mode
        nillableDictionary["passengerType"] = self.passengerType
        nillableDictionary["from"] = self.from
        nillableDictionary["to"] = self.to
        nillableDictionary["fromStation"] = self.fromStation
        nillableDictionary["toStation"] = self.toStation
        nillableDictionary["via"] = self.via
        nillableDictionary["routeCode"] = self.routeCode
        nillableDictionary["displayName"] = self.displayName
        nillableDictionary["displayOrder"] = self.displayOrder?.encodeToJSON()
        nillableDictionary["routeDescription"] = self.routeDescription
        nillableDictionary["validatorInformation"] = self.validatorInformation
        nillableDictionary["operator"] = self._operator
        nillableDictionary["specialFare"] = self.specialFare
        nillableDictionary["throughFare"] = self.throughFare
        nillableDictionary["isTour"] = self.isTour
        nillableDictionary["ticketsAvailable"] = self.ticketsAvailable?.encodeToJSON()
        nillableDictionary["messages"] = self.messages?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
