//
// FaresSection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class FaresSection: JSONEncodable {

    public var header: String?
    public var index: Int32?
    public var rows: [FareDetails]?
    public var messages: [Message]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["header"] = self.header
        nillableDictionary["index"] = self.index?.encodeToJSON()
        nillableDictionary["rows"] = self.rows?.encodeToJSON()
        nillableDictionary["messages"] = self.messages?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
