//
// GeoCodeSearchMatch.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class GeoCodeSearchMatch: JSONEncodable {

    /** The type of the place e.g. \&quot;street_address\&quot; */
    public var types: [String]?
    /** A string describing the formatted address of the place. Adds additional context to the place&#39;s Name. */
    public var address: String?
    public var id: String?
    public var url: String?
    public var name: String?
    public var lat: Double?
    public var lon: Double?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["types"] = self.types?.encodeToJSON()
        nillableDictionary["address"] = self.address
        nillableDictionary["id"] = self.id
        nillableDictionary["url"] = self.url
        nillableDictionary["name"] = self.name
        nillableDictionary["lat"] = self.lat
        nillableDictionary["lon"] = self.lon

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
