//
// GeoPointBBox.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class GeoPointBBox: JSONEncodable {

    public var swLat: Double?
    public var swLon: Double?
    public var neLat: Double?
    public var neLon: Double?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["swLat"] = self.swLat
        nillableDictionary["swLon"] = self.swLon
        nillableDictionary["neLat"] = self.neLat
        nillableDictionary["neLon"] = self.neLon

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
