//
// Instruction.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Instruction: JSONEncodable {

    public var summary: String?
    public var detailed: String?
    public var steps: [InstructionStep]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["summary"] = self.summary
        nillableDictionary["detailed"] = self.detailed
        nillableDictionary["steps"] = self.steps?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
