//
// JourneyPlannerCycleHireDockingStationData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class JourneyPlannerCycleHireDockingStationData: JSONEncodable {

    public var originNumberOfBikes: Int32?
    public var destinationNumberOfBikes: Int32?
    public var originNumberOfEmptySlots: Int32?
    public var destinationNumberOfEmptySlots: Int32?
    public var originId: String?
    public var destinationId: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["originNumberOfBikes"] = self.originNumberOfBikes?.encodeToJSON()
        nillableDictionary["destinationNumberOfBikes"] = self.destinationNumberOfBikes?.encodeToJSON()
        nillableDictionary["originNumberOfEmptySlots"] = self.originNumberOfEmptySlots?.encodeToJSON()
        nillableDictionary["destinationNumberOfEmptySlots"] = self.destinationNumberOfEmptySlots?.encodeToJSON()
        nillableDictionary["originId"] = self.originId
        nillableDictionary["destinationId"] = self.destinationId

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
