//
// Journey.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Object that represents an end to end journey (see schematic). */
open class Journey: JSONEncodable {

    public var startDateTime: Date?
    public var duration: Int32?
    public var arrivalDateTime: Date?
    public var legs: [Leg]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["startDateTime"] = self.startDateTime?.encodeToJSON()
        nillableDictionary["duration"] = self.duration?.encodeToJSON()
        nillableDictionary["arrivalDateTime"] = self.arrivalDateTime?.encodeToJSON()
        nillableDictionary["legs"] = self.legs?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
