//
// JpElevation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class JpElevation: JSONEncodable {

    public var distance: Int32?
    public var startLat: Double?
    public var startLon: Double?
    public var endLat: Double?
    public var endLon: Double?
    public var heightFromPreviousPoint: Int32?
    public var gradient: Double?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["distance"] = self.distance?.encodeToJSON()
        nillableDictionary["startLat"] = self.startLat
        nillableDictionary["startLon"] = self.startLon
        nillableDictionary["endLat"] = self.endLat
        nillableDictionary["endLon"] = self.endLon
        nillableDictionary["heightFromPreviousPoint"] = self.heightFromPreviousPoint?.encodeToJSON()
        nillableDictionary["gradient"] = self.gradient

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
