//
// LineSpecificServiceType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class LineSpecificServiceType: JSONEncodable {

    public var serviceType: LineServiceTypeInfo?
    public var stopServesServiceType: Bool?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["serviceType"] = self.serviceType?.encodeToJSON()
        nillableDictionary["stopServesServiceType"] = self.stopServesServiceType

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
