//
// LineGroup.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class LineGroup: JSONEncodable {

    public var naptanIdReference: String?
    public var stationAtcoCode: String?
    public var lineIdentifier: [String]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["naptanIdReference"] = self.naptanIdReference
        nillableDictionary["stationAtcoCode"] = self.stationAtcoCode
        nillableDictionary["lineIdentifier"] = self.lineIdentifier?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
