//
// MatchedRoute.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class MatchedRoute: JSONEncodable {

    /** The route code */
    public var routeCode: String?
    /** Name such as \&quot;72\&quot; */
    public var name: String?
    /** eg: N or S or I or O */
    public var direction: String?
    /** eg: Origination Name */
    public var originationName: String?
    /** eg: Destination Name */
    public var destinationName: String?
    /** eg: Origination */
    public var originator: String?
    /** eg: Destination */
    public var destination: String?
    /** eg: Regular, Night */
    public var serviceType: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["routeCode"] = self.routeCode
        nillableDictionary["name"] = self.name
        nillableDictionary["direction"] = self.direction
        nillableDictionary["originationName"] = self.originationName
        nillableDictionary["destinationName"] = self.destinationName
        nillableDictionary["originator"] = self.originator
        nillableDictionary["destination"] = self.destination
        nillableDictionary["serviceType"] = self.serviceType

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
