//
// Message.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Message: JSONEncodable {

    public var bulletOrder: Int32?
    public var header: Bool?
    public var messageText: String?
    public var linkText: String?
    public var url: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["bulletOrder"] = self.bulletOrder?.encodeToJSON()
        nillableDictionary["header"] = self.header
        nillableDictionary["messageText"] = self.messageText
        nillableDictionary["linkText"] = self.linkText
        nillableDictionary["url"] = self.url

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
