//
// Mode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Mode: JSONEncodable {

    public var isTflService: Bool?
    public var isFarePaying: Bool?
    public var isScheduledService: Bool?
    public var modeName: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["isTflService"] = self.isTflService
        nillableDictionary["isFarePaying"] = self.isFarePaying
        nillableDictionary["isScheduledService"] = self.isScheduledService
        nillableDictionary["modeName"] = self.modeName

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
