//
// Obstacle.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Obstacle: JSONEncodable {

    public var type: String?
    public var incline: String?
    public var stopId: Int32?
    public var position: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["type"] = self.type
        nillableDictionary["incline"] = self.incline
        nillableDictionary["stopId"] = self.stopId?.encodeToJSON()
        nillableDictionary["position"] = self.position

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
