//
// OrderedRoute.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class OrderedRoute: JSONEncodable {

    public var name: String?
    public var naptanIds: [String]?
    public var serviceType: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["naptanIds"] = self.naptanIds?.encodeToJSON()
        nillableDictionary["serviceType"] = self.serviceType

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
