//
// PassengerType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class PassengerType: JSONEncodable {

    public var type: String?
    public var description: String?
    public var displayName: String?
    public var displayOrder: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["type"] = self.type
        nillableDictionary["description"] = self.description
        nillableDictionary["displayName"] = self.displayName
        nillableDictionary["displayOrder"] = self.displayOrder?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
