//
// Path.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Path: JSONEncodable {

    public var lineString: String?
    public var stopPoints: [Identifier]?
    public var elevation: [JpElevation]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["lineString"] = self.lineString
        nillableDictionary["stopPoints"] = self.stopPoints?.encodeToJSON()
        nillableDictionary["elevation"] = self.elevation?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
