//
// Period.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Period: JSONEncodable {

    public enum ModelType: String { 
        case normal = "Normal"
        case frequencyHours = "FrequencyHours"
        case frequencyMinutes = "FrequencyMinutes"
        case unknown = "Unknown"
    }
    public var type: ModelType?
    public var fromTime: TwentyFourHourClockTime?
    public var toTime: TwentyFourHourClockTime?
    public var frequency: ServiceFrequency?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["type"] = self.type?.rawValue
        nillableDictionary["fromTime"] = self.fromTime?.encodeToJSON()
        nillableDictionary["toTime"] = self.toTime?.encodeToJSON()
        nillableDictionary["frequency"] = self.frequency?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
