//
// PlannedWork.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class PlannedWork: JSONEncodable {

    public var id: String?
    public var description: String?
    public var createdDateTime: Date?
    public var lastUpdateDateTime: Date?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["description"] = self.description
        nillableDictionary["createdDateTime"] = self.createdDateTime?.encodeToJSON()
        nillableDictionary["lastUpdateDateTime"] = self.lastUpdateDateTime?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
