//
// Point.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents a point located at a latitude and longitude using the WGS84 co-ordinate system. */
open class Point: JSONEncodable {

    /** WGS84 latitude of the location. */
    public var lat: Double?
    /** WGS84 longitude of the location. */
    public var lon: Double?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["lat"] = self.lat
        nillableDictionary["lon"] = self.lon

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
