//
// Redirect.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Redirect: JSONEncodable {

    public var shortUrl: String?
    public var longUrl: String?
    public var active: Bool?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["shortUrl"] = self.shortUrl
        nillableDictionary["longUrl"] = self.longUrl
        nillableDictionary["active"] = self.active

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
