//
// RoadCorridor.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class RoadCorridor: JSONEncodable {

    /** The Id of the Corridor e.g. \&quot;A406\&quot; */
    public var id: String?
    /** The display name of the Corridor e.g. \&quot;North Circular (A406)\&quot;. This              may be identical to the Id. */
    public var displayName: String?
    /** The group name of the Corridor e.g. \&quot;Central London\&quot;. Most corridors are not grouped, in which case this field can be null. */
    public var group: String?
    /** Standard multi-mode status severity code */
    public var statusSeverity: String?
    /** Description of the status severity as applied to RoadCorridors */
    public var statusSeverityDescription: String?
    /** The Bounds of the Corridor, given by the south-east followed by the north-west co-ordinate              pair in geoJSON format e.g. \&quot;[[-1.241531,51.242151],[1.641223,53.765721]]\&quot; */
    public var bounds: String?
    /** The Envelope of the Corridor, given by the corner co-ordinates of a rectangular (four-point) polygon              in geoJSON format e.g. \&quot;[[-1.241531,51.242151],[-1.241531,53.765721],[1.641223,53.765721],[1.641223,51.242151]]\&quot; */
    public var envelope: String?
    /** The start of the period over which status has been aggregated, or null if this is the current corridor status. */
    public var statusAggregationStartDate: Date?
    /** The end of the period over which status has been aggregated, or null if this is the current corridor status. */
    public var statusAggregationEndDate: Date?
    /** URL to retrieve this Corridor. */
    public var url: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["displayName"] = self.displayName
        nillableDictionary["group"] = self.group
        nillableDictionary["statusSeverity"] = self.statusSeverity
        nillableDictionary["statusSeverityDescription"] = self.statusSeverityDescription
        nillableDictionary["bounds"] = self.bounds
        nillableDictionary["envelope"] = self.envelope
        nillableDictionary["statusAggregationStartDate"] = self.statusAggregationStartDate?.encodeToJSON()
        nillableDictionary["statusAggregationEndDate"] = self.statusAggregationEndDate?.encodeToJSON()
        nillableDictionary["url"] = self.url

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
