//
// RoadProject.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class RoadProject: JSONEncodable {

    public enum Phase: String { 
        case unscoped = "Unscoped"
        case concept = "Concept"
        case consultationEnded = "ConsultationEnded"
        case consultation = "Consultation"
        case construction = "Construction"
        case complete = "Complete"
    }
    public var projectId: String?
    public var schemeName: String?
    public var projectName: String?
    public var projectDescription: String?
    public var projectPageUrl: String?
    public var consultationPageUrl: String?
    public var consultationStartDate: Date?
    public var consultationEndDate: Date?
    public var constructionStartDate: Date?
    public var constructionEndDate: Date?
    public var boroughsBenefited: [String]?
    public var cycleSuperhighwayId: String?
    public var phase: Phase?
    public var contactName: String?
    public var contactEmail: String?
    public var externalPageUrl: String?
    public var projectSummaryPageUrl: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["projectId"] = self.projectId
        nillableDictionary["schemeName"] = self.schemeName
        nillableDictionary["projectName"] = self.projectName
        nillableDictionary["projectDescription"] = self.projectDescription
        nillableDictionary["projectPageUrl"] = self.projectPageUrl
        nillableDictionary["consultationPageUrl"] = self.consultationPageUrl
        nillableDictionary["consultationStartDate"] = self.consultationStartDate?.encodeToJSON()
        nillableDictionary["consultationEndDate"] = self.consultationEndDate?.encodeToJSON()
        nillableDictionary["constructionStartDate"] = self.constructionStartDate?.encodeToJSON()
        nillableDictionary["constructionEndDate"] = self.constructionEndDate?.encodeToJSON()
        nillableDictionary["boroughsBenefited"] = self.boroughsBenefited?.encodeToJSON()
        nillableDictionary["cycleSuperhighwayId"] = self.cycleSuperhighwayId
        nillableDictionary["phase"] = self.phase?.rawValue
        nillableDictionary["contactName"] = self.contactName
        nillableDictionary["contactEmail"] = self.contactEmail
        nillableDictionary["externalPageUrl"] = self.externalPageUrl
        nillableDictionary["projectSummaryPageUrl"] = self.projectSummaryPageUrl

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
