//
// RoadDisruptionSchedule.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class RoadDisruptionSchedule: JSONEncodable {

    public var startTime: Date?
    public var endTime: Date?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["startTime"] = self.startTime?.encodeToJSON()
        nillableDictionary["endTime"] = self.endTime?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
