//
// RoadDisruptionLine.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class RoadDisruptionLine: JSONEncodable {

    public var id: Int32?
    public var roadDisruptionId: String?
    public var isDiversion: Bool?
    public var multiLineString: DbGeography?
    public var startDate: Date?
    public var endDate: Date?
    public var startTime: String?
    public var endTime: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["roadDisruptionId"] = self.roadDisruptionId
        nillableDictionary["isDiversion"] = self.isDiversion
        nillableDictionary["multiLineString"] = self.multiLineString?.encodeToJSON()
        nillableDictionary["startDate"] = self.startDate?.encodeToJSON()
        nillableDictionary["endDate"] = self.endDate?.encodeToJSON()
        nillableDictionary["startTime"] = self.startTime
        nillableDictionary["endTime"] = self.endTime

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
