//
// RouteSection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class RouteSection: JSONEncodable {

    /** The Id of the route */
    public var id: String?
    /** The Id of the Line */
    public var lineId: String?
    /** The route code */
    public var routeCode: String?
    /** Name such as \&quot;72\&quot; */
    public var name: String?
    /** eg: N or S or I or O */
    public var direction: String?
    /** eg: Path coordindates */
    public var lineString: String?
    /** eg: Origination Name */
    public var originationName: String?
    /** eg: Destination Name */
    public var destinationName: String?
    public var routeSectionNaptanEntrySequence: [RouteSectionNaptanEntrySequence]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["lineId"] = self.lineId
        nillableDictionary["routeCode"] = self.routeCode
        nillableDictionary["name"] = self.name
        nillableDictionary["direction"] = self.direction
        nillableDictionary["lineString"] = self.lineString
        nillableDictionary["originationName"] = self.originationName
        nillableDictionary["destinationName"] = self.destinationName
        nillableDictionary["routeSectionNaptanEntrySequence"] = self.routeSectionNaptanEntrySequence?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
