//
// RouteSearchMatch.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class RouteSearchMatch: JSONEncodable {

    public var lineId: String?
    public var mode: String?
    public var lineName: String?
    public var lineRouteSection: [LineRouteSection]?
    public var matchedRouteSections: [MatchedRouteSections]?
    public var matchedStops: [MatchedStop]?
    public var id: String?
    public var url: String?
    public var name: String?
    public var lat: Double?
    public var lon: Double?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["lineId"] = self.lineId
        nillableDictionary["mode"] = self.mode
        nillableDictionary["lineName"] = self.lineName
        nillableDictionary["lineRouteSection"] = self.lineRouteSection?.encodeToJSON()
        nillableDictionary["matchedRouteSections"] = self.matchedRouteSections?.encodeToJSON()
        nillableDictionary["matchedStops"] = self.matchedStops?.encodeToJSON()
        nillableDictionary["id"] = self.id
        nillableDictionary["url"] = self.url
        nillableDictionary["name"] = self.name
        nillableDictionary["lat"] = self.lat
        nillableDictionary["lon"] = self.lon

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
