//
// RouteOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class RouteOption: JSONEncodable {

    /** The Id of the route */
    public var id: String?
    /** Name such as \&quot;72\&quot; */
    public var name: String?
    public var directions: [String]?
    /** The line identifier (e.g. District Line), from where you can obtain line status information e.g. the rainbow board status \&quot;good service\&quot;. */
    public var lineIdentifier: Identifier?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["directions"] = self.directions?.encodeToJSON()
        nillableDictionary["lineIdentifier"] = self.lineIdentifier?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
