//
// SearchMatch.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SearchMatch: JSONEncodable {

    public var id: String?
    public var url: String?
    public var name: String?
    public var lat: Double?
    public var lon: Double?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["url"] = self.url
        nillableDictionary["name"] = self.name
        nillableDictionary["lat"] = self.lat
        nillableDictionary["lon"] = self.lon

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
