//
// SearchResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SearchResponse: JSONEncodable {

    public var query: String?
    public var from: Int32?
    public var page: Int32?
    public var pageSize: Int32?
    public var provider: String?
    public var total: Int32?
    public var matches: [SearchMatch]?
    public var maxScore: Double?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["query"] = self.query
        nillableDictionary["from"] = self.from?.encodeToJSON()
        nillableDictionary["page"] = self.page?.encodeToJSON()
        nillableDictionary["pageSize"] = self.pageSize?.encodeToJSON()
        nillableDictionary["provider"] = self.provider
        nillableDictionary["total"] = self.total?.encodeToJSON()
        nillableDictionary["matches"] = self.matches?.encodeToJSON()
        nillableDictionary["maxScore"] = self.maxScore

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
