//
// SearchCriteria.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SearchCriteria: JSONEncodable {

    public enum DateTimeType: String { 
        case arriving = "Arriving"
        case departing = "Departing"
    }
    public var dateTime: Date?
    public var dateTimeType: DateTimeType?
    public var timeAdjustments: TimeAdjustments?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["dateTime"] = self.dateTime?.encodeToJSON()
        nillableDictionary["dateTimeType"] = self.dateTimeType?.rawValue
        nillableDictionary["timeAdjustments"] = self.timeAdjustments?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
