//
// StatusSeverity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class StatusSeverity: JSONEncodable {

    public var modeName: String?
    public var severityLevel: Int32?
    public var description: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["modeName"] = self.modeName
        nillableDictionary["severityLevel"] = self.severityLevel?.encodeToJSON()
        nillableDictionary["description"] = self.description

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
