//
// StopPointsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A paged response containing StopPoints */
open class StopPointsResponse: JSONEncodable {

    /** The centre latitude/longitude of this list of StopPoints */
    public var centrePoint: [Double]?
    /** Collection of stop points */
    public var stopPoints: [StopPoint]?
    /** The maximum size of the page in this response i.e. the maximum number of StopPoints */
    public var pageSize: Int32?
    /** The total number of StopPoints available across all pages */
    public var total: Int32?
    /** The index of this page */
    public var page: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["centrePoint"] = self.centrePoint?.encodeToJSON()
        nillableDictionary["stopPoints"] = self.stopPoints?.encodeToJSON()
        nillableDictionary["pageSize"] = self.pageSize?.encodeToJSON()
        nillableDictionary["total"] = self.total?.encodeToJSON()
        nillableDictionary["page"] = self.page?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
