//
// StreetSegment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class StreetSegment: JSONEncodable {

    /** A 16 digit unique integer identifying a OS ITN (Ordnance Survey Integrated Transport Network) road link. */
    public var toid: String?
    /** geoJSON formatted LineString containing two latitude/longitude (WGS84) pairs that identify the start and end points of the street segment. */
    public var lineString: String?
    /** The ID from the source system of the disruption that this street belongs to. */
    public var sourceSystemId: Int64?
    /** The key of the source system of the disruption that this street belongs to. */
    public var sourceSystemKey: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["toid"] = self.toid
        nillableDictionary["lineString"] = self.lineString
        nillableDictionary["sourceSystemId"] = self.sourceSystemId?.encodeToJSON()
        nillableDictionary["sourceSystemKey"] = self.sourceSystemKey

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
