//
// Ticket.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Ticket: JSONEncodable {

    public var passengerType: String?
    public var ticketType: TicketType?
    public var ticketTime: TicketTime?
    public var cost: String?
    public var description: String?
    public var mode: String?
    public var displayOrder: Int32?
    public var messages: [Message]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["passengerType"] = self.passengerType
        nillableDictionary["ticketType"] = self.ticketType?.encodeToJSON()
        nillableDictionary["ticketTime"] = self.ticketTime?.encodeToJSON()
        nillableDictionary["cost"] = self.cost
        nillableDictionary["description"] = self.description
        nillableDictionary["mode"] = self.mode
        nillableDictionary["displayOrder"] = self.displayOrder?.encodeToJSON()
        nillableDictionary["messages"] = self.messages?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
