//
// TimeAdjustments.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class TimeAdjustments: JSONEncodable {

    public var earliest: TimeAdjustment?
    public var earlier: TimeAdjustment?
    public var later: TimeAdjustment?
    public var latest: TimeAdjustment?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["earliest"] = self.earliest?.encodeToJSON()
        nillableDictionary["earlier"] = self.earlier?.encodeToJSON()
        nillableDictionary["later"] = self.later?.encodeToJSON()
        nillableDictionary["latest"] = self.latest?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
