//
// TimetableRoute.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class TimetableRoute: JSONEncodable {

    public var stationIntervals: [StationInterval]?
    public var schedules: [Schedule]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["stationIntervals"] = self.stationIntervals?.encodeToJSON()
        nillableDictionary["schedules"] = self.schedules?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
