//
// TimetableResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class TimetableResponse: JSONEncodable {

    public var lineId: String?
    public var lineName: String?
    public var direction: String?
    public var pdfUrl: String?
    public var stations: [MatchedStop]?
    public var stops: [MatchedStop]?
    public var timetable: Timetable?
    public var disambiguation: Disambiguation?
    public var statusErrorMessage: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["lineId"] = self.lineId
        nillableDictionary["lineName"] = self.lineName
        nillableDictionary["direction"] = self.direction
        nillableDictionary["pdfUrl"] = self.pdfUrl
        nillableDictionary["stations"] = self.stations?.encodeToJSON()
        nillableDictionary["stops"] = self.stops?.encodeToJSON()
        nillableDictionary["timetable"] = self.timetable?.encodeToJSON()
        nillableDictionary["disambiguation"] = self.disambiguation?.encodeToJSON()
        nillableDictionary["statusErrorMessage"] = self.statusErrorMessage

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
