//
// TimeAdjustment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class TimeAdjustment: JSONEncodable {

    public var date: String?
    public var time: String?
    public var timeIs: String?
    public var uri: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["date"] = self.date
        nillableDictionary["time"] = self.time
        nillableDictionary["timeIs"] = self.timeIs
        nillableDictionary["uri"] = self.uri

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
