//
// TrainLoading.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class TrainLoading: JSONEncodable {

    /** The Line Name e.g. \&quot;Victoria\&quot; */
    public var line: String?
    /** Direction of the Line e.g. NB, SB, WB etc. */
    public var lineDirection: String?
    /** Direction displayed on the platform e.g. NB, SB, WB etc. */
    public var platformDirection: String?
    /** Direction in regards to Journey Planner i.e. inbound or outbound */
    public var direction: String?
    /** Naptan of the adjacent station */
    public var naptanTo: String?
    /** Time in 24hr format with 15 minute intervals e.g. 0500-0515, 0515-0530 etc. */
    public var timeSlice: String?
    /** Scale between 1-6,                1 &#x3D; Very quiet, 2 &#x3D; Quiet, 3 &#x3D; Fairly busy, 4 &#x3D; Busy, 5 &#x3D; Very busy, 6 &#x3D; Exceptionally busy */
    public var value: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["line"] = self.line
        nillableDictionary["lineDirection"] = self.lineDirection
        nillableDictionary["platformDirection"] = self.platformDirection
        nillableDictionary["direction"] = self.direction
        nillableDictionary["naptanTo"] = self.naptanTo
        nillableDictionary["timeSlice"] = self.timeSlice
        nillableDictionary["value"] = self.value?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
