//
// ValidityPeriod.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents a period for which a planned works is valid. */
open class ValidityPeriod: JSONEncodable {

    /** Gets or sets the start date. */
    public var fromDate: Date?
    /** Gets or sets the end date. */
    public var toDate: Date?
    /** If true is a realtime status rather than planned or info */
    public var isNow: Bool?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["fromDate"] = self.fromDate?.encodeToJSON()
        nillableDictionary["toDate"] = self.toDate?.encodeToJSON()
        nillableDictionary["isNow"] = self.isNow

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
